---
title: "Twitter Data with rtweet"
author: "Team Hanley NLP Working Group"
output:
  html_document:
    toc: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting Started

### Getting a Developer Account
caitlin -  youtube video

### Saving Credentials in a .gitignore
After finally getting your credentials, you need to protect them. If you are just working locally on your computer, this is easy. Just do whatever you usually do to protect complicated passwords. However, if you are working on a git project (like this one), then you need to do something extra.

Luckily, the process is very simple. (1) Save your credentials in a different script and (2) add that script into your .gitignore, and then (3) add that script into the .gitignore. 

**Save your credentials into a script called keys.R**
```{}
# twitter
twitter_api_key = "sample_key"
twitter_api_secret_key = "sample_key"
twitter_access_token = "sample_key"
twitter_access_token_secret = "sample_key"

```

**Create a .gitignore file**

This part is a little more complicated than you may expect because you are just creating a file. But I think the most reproducible way is through git bash. In the root directory of your project, open up bash (right click and press "Git Bash Here"), and write the following code:

`touch .gitignore`

**Add script into your .gitignore and then call it into your project**
Just open up the .gitignore (notepad works fine), and add keys.R into the .gitignore file. Now if you are simply just writing `keys.R` into the file, than it has to be in the same directory. There are a bunch of different options for (.gitignore)[https://www.atlassian.com/git/tutorials/saving-changes/gitignore]. Finally, make sure that you 

## rtweet

`rtweet` is a package designed to interact with twitter's API. It is tidyverse ready meaning that its API calls return a data.frame. This is really convienient if your workflow includes things like `dplyr` or `tidytext`.

### Retrieving Topics
caitlin

### User Data
caitlin

### Posting a tweet
Corydon



## TwitteR

### Retrieving Topics

Michael Bunting

### User Tweets

Michael Bunting



## Example 1: For users 

## Example 2:

## Conclusion
